# Generated by Django 4.2.14 on 2024-08-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='institution',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
