# Generated by Django 4.2.14 on 2024-08-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_book_totalrating_remove_book_totalreview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='semester',
        ),
    ]
