# Generated by Django 4.2.14 on 2024-08-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_name_category_subject_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Semester',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Subject',
        ),
    ]
