# Generated by Django 4.2.14 on 2024-08-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_subcategory_semester_rename_category_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
