# Generated by Django 4.2.14 on 2024-08-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='regulations',
            field=models.CharField(choices=[('', 'Choose Your semerter'), ('16', '2016'), ('22', '2022')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='semester',
            field=models.CharField(choices=[('', 'Choose Your semerter'), ('FS', 'First'), ('SD', 'Second'), ('TH', 'Third'), ('FR', 'Fourth'), ('FI', 'Fifth'), ('SI', 'Sixth'), ('SE', 'Seventh')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(choices=[('', 'Choose Your subject'), ('CMT', 'Computer'), ('CE', 'Civil '), ('ET', 'Electrical'), ('ENT', 'Electronics'), ('ME', 'Mechanical'), ('FT', 'Food'), ('RAC', 'RAC'), ('MCT', 'Mechatronics')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
